require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ZoosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Zoo. As you add validations to Zoo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'Big Zoo'}
  }

  let(:invalid_attributes) {
    {name: ''}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ZoosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all zoos as @zoos" do
      zoo = Zoo.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:zoos)).to eq([zoo])
    end
  end

  describe "GET #show" do
    it "assigns the requested zoo as @zoo" do
      zoo = Zoo.create! valid_attributes
      get :show, {:id => zoo.to_param}, valid_session
      expect(assigns(:zoo)).to eq(zoo)
    end
  end

  describe "GET #new" do
    it "assigns a new zoo as @zoo" do
      get :new, {}, valid_session
      expect(assigns(:zoo)).to be_a_new(Zoo)
    end
  end

  describe "GET #edit" do
    it "assigns the requested zoo as @zoo" do
      zoo = Zoo.create! valid_attributes
      get :edit, {:id => zoo.to_param}, valid_session
      expect(assigns(:zoo)).to eq(zoo)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Zoo" do
        expect {
          post :create, {:zoo => valid_attributes}, valid_session
        }.to change(Zoo, :count).by(1)
      end

      it "assigns a newly created zoo as @zoo" do
        post :create, {:zoo => valid_attributes}, valid_session
        expect(assigns(:zoo)).to be_a(Zoo)
        expect(assigns(:zoo)).to be_persisted
      end

      it "redirects to the created zoo" do
        post :create, {:zoo => valid_attributes}, valid_session
        expect(response).to redirect_to(Zoo.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved zoo as @zoo" do
        post :create, {:zoo => invalid_attributes}, valid_session
        expect(assigns(:zoo)).to be_a_new(Zoo)
      end

      it "re-renders the 'new' template" do
        post :create, {:zoo => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested zoo" do
        zoo = Zoo.create! valid_attributes
        put :update, {:id => zoo.to_param, :zoo => new_attributes}, valid_session
        zoo.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested zoo as @zoo" do
        zoo = Zoo.create! valid_attributes
        put :update, {:id => zoo.to_param, :zoo => valid_attributes}, valid_session
        expect(assigns(:zoo)).to eq(zoo)
      end

      it "redirects to the zoo" do
        zoo = Zoo.create! valid_attributes
        put :update, {:id => zoo.to_param, :zoo => valid_attributes}, valid_session
        expect(response).to redirect_to(zoo)
      end
    end

    context "with invalid params" do
      it "assigns the zoo as @zoo" do
        zoo = Zoo.create! valid_attributes
        put :update, {:id => zoo.to_param, :zoo => invalid_attributes}, valid_session
        expect(assigns(:zoo)).to eq(zoo)
      end

      it "re-renders the 'edit' template" do
        zoo = Zoo.create! valid_attributes
        put :update, {:id => zoo.to_param, :zoo => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested zoo" do
      zoo = Zoo.create! valid_attributes
      expect {
        delete :destroy, {:id => zoo.to_param}, valid_session
      }.to change(Zoo, :count).by(-1)
    end

    it "redirects to the zoos list" do
      zoo = Zoo.create! valid_attributes
      delete :destroy, {:id => zoo.to_param}, valid_session
      expect(response).to redirect_to(zoos_url)
    end
  end

end
